services:
  pixel-deck:
    build:
      context: .                            # Path to the build context (project root)
      dockerfile: Dockerfile                # Dockerfile used to build the image
    container_name: pixel-deck              # Name of the container

    privileged: true                        # Grants extended privileges (required for direct GPIO access on Raspberry Pi)
    devices:
      - "/dev/mem:/dev/mem"                 # Maps physical memory device (needed for low-level LED matrix control)

    environment:
      TZ: Europe/Prague                     # Sets container timezone

    working_dir: /app                       # Working directory inside the container

    volumes:
      - ./config.yml:/app/config.yml:ro     # Mounts configuration file (read-only)
      - ./assets:/app/assets:ro             # Mounts assets (images, fonts, etc.) (read-only)

    command: ["python3", "main.py"]         # Command executed when container starts

    restart: "no"                           # Do not automatically restart the container on exit